"""Constants for DS2 protocol."""

# ECU Addresses
MOTRONIC = 0x12
AUTOMATIC_TRANSMISSION = 0x32
IKE = 0x80
LCM = 0xD0

# Command IDs
CMD_SET_ANALOG = 0x0C
CMD_READ_MEMORY = 0x06
CMD_WRITE_MEMORY = 0x07
CMD_ACTIVATE_TEST = 0x30
CMD_DEACTIVATE_TEST = 0x9F

# Status Codes
STATUS_OKAY = 0xA0
STATUS_BUSY = 0xA1
STATUS_ERROR_ECU_REJECTED = 0xA2
STATUS_ERROR_ECU_PARAMETER = 0xB0
STATUS_ERROR_ECU_FUNCTION = 0xB1
STATUS_ERROR_ECU_NUMBER = 0xB2
STATUS_ERROR_ECU_NACK = 0xFF

# Memory Types
MEMORY_TYPE_ROM = 0x01
MEMORY_TYPE_EEPROM = 0x03
MEMORY_TYPE_INTERNAL_RAM = 0x04
MEMORY_TYPE_EXTERNAL_RAM = 0x05
MEMORY_TYPE_DPRAM = 0x0A

# Memory Type Names
MEMORY_TYPE_NAMES = {
    "rom": MEMORY_TYPE_ROM,
    "eeprom": MEMORY_TYPE_EEPROM,
    "internalram": MEMORY_TYPE_INTERNAL_RAM,
    "externalram": MEMORY_TYPE_EXTERNAL_RAM,
    "dpram": MEMORY_TYPE_DPRAM,
}
